/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.centralenantes.tp_pgm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author remir
 */
public class Window extends javax.swing.JFrame {
    
    
    private ImagePGM currentImage;
    private ImagePGM newImage;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileName = new javax.swing.JLabel();
        currentFile = new javax.swing.JLabel();
        newFile = new javax.swing.JLabel();
        newFileInfo = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        treatment = new javax.swing.JMenu();
        histogram = new javax.swing.JMenuItem();
        resize = new javax.swing.JMenuItem();
        seuil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fileName.setText("None");

        currentFile.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        currentFile.setText("Current File");

        newFile.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        newFile.setText("New File");

        newFileInfo.setText("None");

        fileMenu.setText("File");

        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        fileMenu.add(open);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        fileMenu.add(save);

        MenuBar.add(fileMenu);

        treatment.setText("Treatment");

        histogram.setText("Generate histogram");
        treatment.add(histogram);

        resize.setText("Resize");
        resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeActionPerformed(evt);
            }
        });
        treatment.add(resize);

        seuil.setText("Seuil");
        seuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seuilActionPerformed(evt);
            }
        });
        treatment.add(seuil);

        MenuBar.add(treatment);

        setJMenuBar(MenuBar);
        MenuBar.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newFileInfo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fileName, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileName)
                    .addComponent(currentFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFile)
                    .addComponent(newFileInfo))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        JFileChooser fileExplorer = new JFileChooser();
        int res = fileExplorer.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION){
            File file = fileExplorer.getSelectedFile();
            try {
                ImagePGM img = new ImagePGM(file);
                currentImage = img;
                String info = file.getName()+"  "+img.getWidth()+"X"+img.getWidth();
                fileName.setText(info);
                // Reset
                newFileInfo.setText("None");
                newImage = null;
                
                
            } catch (Exception ex) {
                Logger.getLogger(TP_PGM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_openActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        JFileChooser fileExplorer = new JFileChooser();
        int res = fileExplorer.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File file = fileExplorer.getSelectedFile();
            //newImage.save(file);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void seuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seuilActionPerformed
        if (currentImage != null) {
            String seuil_value = JOptionPane.showInputDialog("Entrer la valeur du seuil (entre 0 et 255)");
            newImage = currentImage.Seuillage(Integer.parseInt(seuil_value));
            if (newImage != null) {
                this.newFileInfo.setText("Seuil "+ seuil_value +"  "+newImage.getWidth()+"X"+newImage.getHeight());
            }
        }
        
    }//GEN-LAST:event_seuilActionPerformed

    private void resizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeActionPerformed
        if (currentImage != null) {
            String factor_value = JOptionPane.showInputDialog("Entrer la valeur du facteur");
            newImage = currentImage.Resize(Integer.parseInt(factor_value));
            if (newImage != null) {
                this.newFileInfo.setText("Resize "+ factor_value +"  "+newImage.getWidth()+"X"+newImage.getHeight());
            }
        }
    }//GEN-LAST:event_resizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel currentFile;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel fileName;
    private javax.swing.JMenuItem histogram;
    private javax.swing.JLabel newFile;
    private javax.swing.JLabel newFileInfo;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem resize;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem seuil;
    private javax.swing.JMenu treatment;
    // End of variables declaration//GEN-END:variables

}
